### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by sbstndb** [JuliaSmoothOptimizers/MUMPS.jl#119]
From `convenience.jl`, I call the function `mumps_solve!(x::AbstractArray, mumps::Mumps, rhs::AbstractArray)`. There is the error `UndefVarError: provide_rhs! not defined`.

`provide_rhs! ` is never defined in the module. 

There are also other functions which call `provide_rhs!` and they do not work.

**Comment by amontoison** [comment]
Solved by #119
