### ISSUE TITLE
Status of Linux support

### ISSUE THREAD

**Issue by rleegates** [JuliaSmoothOptimizers/MUMPS.jl#2]
Hi Dominique,

we're looking to use MUMPS.jl on Linux systems. I was just wondering how Linux support is coming along and when we may expect it to be functioning.

Best regards,
Robert

**Comment by dpo** [comment]
Linux support is already there. The badge says that the build fails because I hit a snag that I believe is due to my misunderstanding of Travis-CI builds (https://travis-ci.org/dpo/MUMPS.jl/jobs/46465198#L906). In my current build file, I use Linuxbrew so that the process on Linux is identical to OSX (minus the bottles). I'd like to hear how it's going for you if you give it a try!

**Comment by rleegates** [comment]
Thanks for the info. As I'm not the admin on the Linux system in question, I can't really speak about the troubles encountered during the installation in a qualified manner. I'll ask our system administrator where the MUMPS build is failing :)

**Comment by dpo** [comment]
You can install Linuxbrew in your account and brew Mumps there, at least as a sanity check. `MUMPS.jl` will also install in your account.

**Comment by rleegates** [comment]
I understand. However, I don't use our Linux systems :)

**Comment by dpo** [comment]
Seems like Travis now builds this extension correctly on Linux:
https://travis-ci.org/dpo/MUMPS.jl/jobs/50706451

**Comment by rleegates** [comment]
Hi Dominique,

thank you, the build workflow could be of help. As far as I'm informed, our admin hasn't been successful at building MUMPS via Linuxbrew on SUSE Linux. I haven't had the time to try myself yet. I'll report back once I get to that :)

Best regards,
Robert

**Comment by dpo** [comment]
The Linuxbrew workflow is apparent [here](https://github.com/dpo/MUMPS.jl/blob/master/.travis.yml). It is also possible to not use Linuxbrew at all and `apt-get install` the parallel version of MUMPS linked with SCOTCH. I was experimenting with that today on CentOS but encountered a fatal error (related to MPI). The problem with that approach is that the debs have unpredictable names so it's difficult for me to give specific instructions.

At any rate, please report your experience when you get to that.

**Comment by rleegates** [comment]
I will look at the installation for linux systems in the next few days. In the meantime I still get MUMPS output with `verbose=false`: `PANEL: INIT and force STRAT_IO=            4`. The call syntax is:
```julia
mumps = Mumps{Float64}(mumps_definite, get_icntl(ooc=true, verbose=false), default_cntl64)
```

**Comment by dpo** [comment]
I'm surprised. I don't get any output:
````
julia> using MUMPS, MPI
julia> MPI.Init()
julia> mumps = Mumps{Float64}(mumps_definite, get_icntl(ooc=true, verbose=false), default_cntl64);
julia> factorize(mumps, spdiagm([1,2,3,4]));
julia> solve(mumps, [1,2,3,4]);
julia> finalize(mumps);
julia>
````
Is there anything else going on in your script?

On OSX, you can [try out MUMPS 5](https://github.com/Homebrew/homebrew-science/pull/1864) if you'd like.

On Linux, you might want to try the [nolib](https://github.com/dpo/MUMPS.jl/tree/nolib) branch if you use Ubuntu or Debian. It doesn't require LinuxBrew and will `apt-get install mumps` instead.

**Comment by rleegates** [comment]
We currently hack a conditional MUMPS import, however, the output occurs without the hack also.

Initialization:
```julia
eval(Expr(:import,:MPI))
	Main.MPI.Init()
	try
		disp = solve()
	finally
		Main.MPI.Finalize()
	end
```

Soluting
```julia
# Hack to import MUMPS conditionally
		# into the Main module, this is a workaround
		# until https://github.com/JuliaLang/julia/pull/6884
		# is merged
		if !isdefined(:MUMPS)
			eval(Expr(:import,:MUMPS))
		end
		mumps = Main.MUMPS.Mumps{Float64}(Main.MUMPS.mumps_definite, Main.MUMPS.get_icntl(ooc=true, verbose=false), Main.MUMPS.default_cntl64)
		try
			Main.MUMPS.associate_matrix(mumps, A)
			Main.MUMPS.factorize(mumps)
			Main.MUMPS.associate_rhs(mumps, rhs)
			Main.MUMPS.solve(mumps)
			dUtmp = Main.MUMPS.get_solution(mumps)
			# other code
		finally
			Main.MUMPS.finalize(mumps)
		end
```

**Comment by dpo** [comment]
Found it. It's a `write()` that's hard-wired in MUMPS itself (in `[sdcz]mumps_part5.F`), and sent to standard output irrespective of the verbosity level. It seems to have been fixed in MUMPS 5, which is why I wasn't observing any output.

**Comment by rleegates** [comment]
Thanks, has your bottle been merged? `brew update` & `brew upgrade mumps` says that 4.10.0_1 ist the latest version.

**Comment by rleegates** [comment]
Sorry, got it. For those who care:

`brew install https://raw.githubusercontent.com/dpo/homebrew-science/mumps5/mumps.rb`

All brew tests run fine, however upon removing/cloning/building MUMPS.jl and running `Pkg.test("MUMPS")`, I get:

```
INFO: Testing MUMPS
julia(27460,0x7fff7daa4300) malloc: *** error for object 0x7fe17cf59590: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
```

**Comment by dpo** [comment]
Thought I fixed that this morning. What's the output of
````
cat $(julia -E 'Pkg.dir()' | sed -e 's/"//g')/MUMPS/deps/deps.jl
````

**Comment by rleegates** [comment]
no such file or directory - the only thing in deps is build.jl

**Comment by dpo** [comment]
I see. The simplified C interface to MUMPS is now installed as part of the Homebrew formula. In the folder `$(julia -E 'Pkg.dir()' | sed -e 's/"//g')/MUMPS`, make sure you change to the `nolib` branch (`git checkout nolib`). That should pick up the C interface from the Cellar. Simply rerun `Pkg.build("MUMPS")` and check the contents of the above file.

**Comment by rleegates** [comment]
```
Coruscant:MUMPS rgates$ git checkout nolib
Branch nolib set up to track remote branch nolib from origin.
Switched to a new branch 'nolib'
Coruscant:MUMPS rgates$ julia
julia> Pkg.build("MUMPS")
INFO: Building Homebrew
remote: Counting objects: 76, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 76 (delta 59), reused 64 (delta 47), pack-reused 0
Unpacking objects: 100% (76/76), done.
From https://github.com/Homebrew/homebrew
   a66474d..c570906  master     -> origin/master
HEAD is now at c570906 git-fixup: add 1.0.0 bottle.
HEAD is now at d3dcfbb Tweak inreplace rules a little so we don't fail on them
Uninstalling cmake...
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.1.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake-3.1.3.yosemite.bottle.tar.gz
🍺  /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/cmake/3.1.3: 1821 files, 30M
To relink: brew unlink cmake && brew link cmake
INFO: Building MPI
INFO: Building MUMPS
================================================[ ERROR: MUMPS ]=================================================

None of the selected providers can install dependency libscalapack.
Use BinDeps.debug(package_name) to see available providers

while loading /Volumes/rgates/.julia/v0.3/MUMPS/deps/build.jl, in expression starting on line 53

=================================================================================================================
```

**Comment by dpo** [comment]
`scalapack` is a dependency of `mumps`. Isn't there a `/usr/local/lib/libscalapack.dylib`?

**Comment by rleegates** [comment]
```
Coruscant:~ rgates$ ls /usr/local/lib/ | grep scalapack
libscalapack.a
```

**Comment by dpo** [comment]
````
brew log scalapack
commit 4ce80dfd460b36c15006cc5b355298e81d64220b
Author: Dominique Orban <dominique.orban@gmail.com>
Date:   Wed Feb 18 23:24:07 2015 -0500

    Scalapack: always build shared libs.

    Closes #1855.

    Signed-off-by: Dominique Orban <dominique.orban@gmail.com>
````

**Comment by dpo** [comment]
Sorry that was a bit fast. By that I meant that your Homebrew is outdated. Run `brew update` and `brew uninstall scalapack mumps` followed by `brew install mumps`. Then in Julia, `Pkg.build("MUMPS")`.

**Comment by rleegates** [comment]
Hi Dominique,

finally got back to this. I've uninstalled scalapack & the old mumps, ran a `brew update`. `brew test mumps` & `Pkg.test("MUMPS") works, however I had to reinstall scalapack manually which was apparently not detected as a dependency, and the `git checkout nolib` hack was still needed. Thank you very much for your help :) - I'll walk over to a colleagues Linux box and see if there's any change on that front... 

Best,
Robert

**Comment by dpo** [comment]
Thanks for the feedback! I'm quite surprised `scalapack` wasn't detected as a dependency. I wonder what happened there. Yes, the `git checkout nolib` hack is still necessary because I haven't yet merged this new procedure into the main branch. Your feedback is much appreciated in that respect!

**Comment by dpo** [comment]
Closing this as Linuxbrew builds MUMPS correctly now: https://github.com/Homebrew/homebrew-science/pull/4520. Please open a new issue if there are still problems. Thanks.
