### ISSUE TITLE
LoadError: None of the selected providers can install dependency libmumps_common.

### ISSUE THREAD

**Issue by truckmyhat** [JuliaSmoothOptimizers/MUMPS.jl#31]
When building MUMPS, I get the following error: 

`==========================================[ ERROR: MUMPS ]==========================================

LoadError: None of the selected providers can install dependency libmumps_common.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\username\AppData\Local\JuliaPro-0.6.4.1\pkgs-0.6.4.1\v0.6\MUMPS\deps\build.jl, i
n expression starting on line 39

====================================================================================================

==========================================[ BUILD ERRORS ]==========================================

WARNING: MUMPS had build errors.

 - packages with build errors remain installed in C:\Users\username\AppData\Local\JuliaPro-0.6.4.1\pkgs
-0.6.4.1\v0.6
 - build the package(s) and all dependencies with `Pkg.build("MUMPS")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================`

Any idea what I can do to get MUMPS to install correctly?

**Comment by dpo** [comment]
On what platform is this?

**Comment by truckmyhat** [comment]
> 
> 
> On what platform is this?

This is on windows 10

**Comment by dpo** [comment]
Ah, sorry, we don't support Windows. However, if you know how to build MUMPS on Windows, I'd be happy to review a pull request.

**Comment by truckmyhat** [comment]
> 
> 
> Ah, sorry, we don't support Windows. However, if you know how to build MUMPS on Windows, I'd be happy to review a pull request.

Ok thanks for the info!
