### ISSUE TITLE
Incorporating MUMPS3

### ISSUE THREAD

**Issue by wrs28** [JuliaSmoothOptimizers/MUMPS.jl#46]
Opening new thread here, because we seem to be opening new topic from the original of [JuliaSparse/MUMPS #21](https://github.com/JuliaSparse/MUMPS.jl/issues/21#issuecomment-497774032).

@dpo I just made some edits to [`MUMPS3`](https://github.com/wrs28/MUMPS3.jl) per your comments. It now links directly to 'lib[sdcz]mumps.dylib', without reference to `mumps_simple`.

Re: doing away with `gc_haven`. It depends on what you mean by "do away with". From the [Julia docs](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Garbage-Collection-Safety-1):

> If a C API will store a reference to memory allocated by Julia, after the ccall returns, you must arrange that the object remains visible to the garbage collector. The suggested way to handle this is to make a global variable of type Array{Ref,1} to hold these values, until the C library notifies you that it is finished with them.

If you don't have *something* like `gc_haven`, the garbage collection wreaks havoc (causing unreproducible behavior and seg faults) when you try to dereference any of the pointers that MUMPS uses. So the solution phase will work fine without this, but Julia might seg fault when you try to access the solution. That said, we can certainly do better than the previous implementation of `gc_haven`, which was very clunky.

The updates I just pushed take the suggestion of the Julia docs more literally, and greatly simplify handling the garbage collection from what it was. Now there is just a single `Mumps` structure with all the MUMPS fields, plus two more. One, called `_finalized`, is a boolean flag to keep track of whether the instance has been previously finalized, the other, `_gc_haven`, is an `Array{Ref,1}`. Because it is just an array of refs it wastes essentially no space, and because it is not a structure with its own fixed fields, the `_gc_haven` code will not need to be updated between versions of MUMPS. All told I think this is a big improvement.

Re: merging improvements with JSO/MUMPS: I'm all in, though I think ultimately there should only be one point of contact with MUMPS: it should be all `mumps_simple` or all native MUMPS C-API. Otherwise it will be hard to debug/maintain in the future, since some features will link to one custom dylib, and other features to a different set. It's just a lot of moving pieces. Thoughts? Obviously I'm partial to using the native MUMPS C-API.

Here's a sketch for merging:
* [ ] decide how we want to interface with MUMPS
   * [ ] if `mumps_simple`, need to expand its capability before we can include new features, which doesn't seem ideal
* [ ] merge capabilities that JSO/MUMPS does not yet have. This would be things like sparse rhs, Schur complement, select entries of the inverse. Since they do not have a predecessor in JSO/MUMPS, they should not conflict with anything, and should be easy to merge.
* [ ] merge capabilities that JSO/MUMPS already has
  * [ ] identify which methods conflict between the two APIs. Upon examining both, decide which method name is more appropriate, giving priority to the previously existing one. In cases where the `MUMPS3` method name/signature (or an entirely new one) is preferred, mark the old signature as deprecated so current users have time to adjust.
  * [ ] modify the underlying code to be consistent with either `mumps_simple` or C-API. The goal is to transition without the user even noticing that something has changed.
  * [ ] identify which methods do *not* conflict between the two APIs. I advocate including *all* such methods at first, since some of my current code in other projects depends on `MUMPS3` :). Temporarily there might be two methods that achieve essentially the same thing. Since that doesn't actually break anyone's existing code, I advocate we leave the "trimming" for later.
  * [ ] trimming: if two methods do the same thing, decide which name/signature we want to keep, and transition the underlying code.

**Comment by wrs28** [comment]
Forgot to mention, re: maintenance: I was hoping you'd say something like that!

**Comment by dpo** [comment]
At long last there is progress here. I rebased your PR in #64 and made adjustments for MUMPS 5.4.1.

**Comment by amontoison** [comment]
`_gc_heaven` and `_finalized` attributes are excellent ideas!
I propose to move to to C-API, it will be easier to support the future releases of MUMPS.

**Comment by dpo** [comment]
I agree that we should move to the C-API. We also need to make choices regarding the naming of methods. In the Fortran library, there is only one subroutine to call: `[SDCZ]MUMPS()` with different values of `JOB`, and control parameters.

In #64, `provide_matrix` seems to be the same as `associate_matrix`. If we kept `associate_matrix`, we would avoid having to mark it deprecated and remove it later. Same with `provide_rhs` and `associate_rhs`. The `provide_` variants don't appear in the unit tests. I suggest we keep `associate_matrix` and `associate_rhs`.

**Comment by dpo** [comment]
MERGED!

**Comment by dpo** [comment]
Many, many thanks!
