### ISSUE TITLE
Ability to get inertia from LDL factorization

### ISSUE THREAD

**Issue by ohinder** [JuliaSmoothOptimizers/MUMPS.jl#5]
It would be useful if it was possible to get the inertia of the factorization (the number of positive and negative values in D which is equivalent to the number of positive and negative eigenvalues in the original matrix https://en.wikipedia.org/wiki/Sylvester%27s_law_of_inertia). It is commonly used in optimization to determine if a problem is convex.

**Comment by dpo** [comment]
`mumps.infog[12]` should give the total number of negative or off-diagonal pivots after the factorization has completed.

**Comment by ohinder** [comment]
excellent! thanks!

**Comment by anitescu** [comment]
If one wants to get P,L,D would that be possible? For example when modifying D to work with line search as in Nocedal and Wright, chapter 3. Sorry if it is obvious, I do not seem to see examples in the tests or documentation.

**Comment by dpo** [comment]
Unfortunately, MUMPS doesn't give access to the factors. It doesn't have a facility to modify D either, though I've submitted that as a feature request several times in the past...

**Comment by anitescu** [comment]
Thanks for the information.
