### ISSUE TITLE
BinaryBuilder libraries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaSmoothOptimizers/MUMPS.jl#53]
Would be nice to at least get the sequential mumps into binarybuilder.

**Comment by dpo** [comment]
This is the parallel mumps though. We need MPI.

**Comment by ViralBShah** [comment]
I would love to start getting MPI into BB too.

**Comment by ViralBShah** [comment]
MPICH.jl is getting into shape in BB.

**Comment by dpo** [comment]
Please don't despair, people. I'm definitely planning to work MUMPS_jll into this package in the near future...

**Comment by ViralBShah** [comment]
@dpo Do we have all the underlying pieces now for this? I keep losing track of which variants of MUMPS we have built in BB. Perhaps the MPI variant has yet to be built.

**Comment by dpo** [comment]
Yes, we have all the missing pieces. MUMPS@5 should be the right one for this repo.

**Comment by amontoison** [comment]
Tests passed with the version `5.5.1` of MUMPS_jll !
