### ISSUE TITLE
Pkg.build without admin rights on Linux

### ISSUE THREAD

**Issue by lruthotto** [JuliaSmoothOptimizers/MUMPS.jl#7]
I'm trying to install MUMPS on a shared workstation on which I don't have admin rights. Installing MUMPS using linuxbrew was not a problem, but Pkg.build fails with the following message

```
Installing dependency libmumps-dev via `sudo apt-get install libmumps-dev`:
sudo: no tty present and no askpass program specified
================================[ ERROR: MUMPS ]================================

LoadError: failed process: Process(`sudo apt-get install libmumps-dev`, ProcessExited(1)) [1]
while loading /home/lruthot/.julia/v0.4/MUMPS/deps/build.jl, in expression starting on line 53

================================================================================
```

This suggests that libmumps-dev needs to be installed via apt-get. This might be a naive question, but shouldn't libmumps-dev be installed by linuxbrew for me?

**Comment by lruthotto** [comment]
ok, I got our admin to install libmumps-dev. So, I'm good for now. Would still be curious if there is another way.

**Comment by dpo** [comment]
I'll look into it when I can (not in the next few days) but there should be no need to install `libmumps-dev` if you already installed MUMPS with Linuxbrew. That's a bug I believe.

**Comment by dpo** [comment]
If you still have the chance, could you try installing MUMPS with Linuxbrew and, without installing `libmumps-dev`, running
```julia
using BinDeps
BinDeps.debug("MUMPS")
```

**Comment by lruthotto** [comment]
not so easy right now, since I don't have admin rights on that machine. will try that next time I'm working on Amazon EC2.

**Comment by dpo** [comment]
Closing this. The CI scripts use Linuxbrew on TravisCI and Circle-CI and show how to get things working without admin privileges.
