### ISSUE TITLE
Cannot build MUMPs on Mac

### ISSUE THREAD

**Issue by artkuo** [JuliaSmoothOptimizers/MUMPS.jl#86]
I tried to update and build failed. Error was `could not load library "libsmumps.dylib"`, because it could not load `/usr/local/opt/gcc/lib/gcc/11/libquadmath.0.dylib` (although I do have `/12/libquadmath.0.dylib`). Occasionally homebrew packages expect a different gcc than what one might have. (I know how to install gcc11, but I don't know where libquadmath comes from.)

So I tried to build from source with `brew reinstall -s mpich-mumps` hoping it would find and link to the right library. It does download `https://github.com/dpo/mumps_simple/archive/v0.4.tar.gz`, but then fails here

> ==> Downloading http://mumps.enseeiht.fr/MUMPS_5.4.1.tar.gz
curl: (56) Recv failure: Connection reset by peer
Error: Failed to download resource "mpich-mumps"
Download failed: http://mumps.enseeiht.fr/MUMPS_5.4.1.tar.gz`

It seems that there is no such server `mumps.enseeiht.fr`, although there is one at `graal.ens-lyon.fr` with a newer version 5.5.1. However, it appears that you need to request a license from `https://graal.ens-lyon.fr/MUMPS/index.php?page=dwnld`. I haven't requested a license, because I wanted to ask if there's are other solutions. For example, is it possible to install 11/libquadmath.0.dylib, or is there a way to get a newer libsmumps.dylib that links to 12/libquadmath?

**Comment by dpo** [comment]
HI @artkuo. The MUMPS home site appears to have been down for a couple of weeks. It sounds like a silly situation where the person maintaining the website is on vacation (!!!). I would think it's temporary.

libquadmath comes with gfortran, which comes with gcc. In my case,
```
$ ll /opt/homebrew/Cellar/gcc/11.3.0_1/lib/gcc/11/libquadmath.*
/opt/homebrew/Cellar/gcc/11.3.0_1/lib/gcc/11/libquadmath.0.dylib  /opt/homebrew/Cellar/gcc/11.3.0_1/lib/gcc/11/libquadmath.a        /opt/homebrew/Cellar/gcc/11.3.0_1/lib/gcc/11/libquadmath.dylib@
```
I believe the `mpich-mumps` bottles were built against gcc-11 and you seem to have gcc-12. I'll try and rebuild the bottles, but with the MUMPS website down ...

We've been working towards a JLL but there are some hurdles.

**Comment by artkuo** [comment]
I think I'll wait this one out. I tried to brew gcc@11, but it didn't provide a `11/libquadmath`, and linking against `12/libquadmath` doesn't seem to work. Seems most straightforward to see if `enseeiht.fr` comes back up. I'll try to check periodically and report back when it happens. Thanks.

**Comment by amontoison** [comment]
You can download the version 5.5.1 of MUMPS with this [link](https://graal.ens-lyon.fr/MUMPS/MUMPS_5.5.1.tar.gz).

**Comment by dpo** [comment]
@artkuo If you would like to try the version in the `main` branch of this repository, we now support precompiled binaries, so you won't need to install MUMPS at all! Please let us know if that works for you.

**Comment by dpo** [comment]
We can now build on Mac Intel and Silicon. Please open a new issue if you are still having difficulties.

**Comment by artkuo** [comment]
Great! I have now verified on Julia 1.7.2 and 1.8.0. I was able to `add MUMPS` successfully. This previously didn't work, which had led me to attempt `mpich-mumps`, also unsuccessfully. Now I have also gone back and used homebrew to install `mpich-mumps`, followed by building `MUMPS` in Julia. Successful, passed tests. Thanks for your help and your great work!
